export const BOARD_IMAGE = {
  THUMB_NAIL_SIZE: '100x100',
};

export const REVIEW_IMAGE = {
  LIMIT_COUNT: 10,
  LIMIT_MEGA_BYTES: 5,
};

export const PERSONAL_INQUIRY_IMAGE = {
  LIMIT_COUNT: 10,
  LIMIT_MEGA_BYTES: 5,
};
